### ISSUE TITLE
TODO novembre 2017

### ISSUE THREAD

**Issue by edmBernard** [edmBernard/DockerFiles#2]
- [x] Add Pytorch
- [x] update mxnet android (last change break compilation)
- [x] add generation script in readme
- [x] update image list in readme
- [x] list of fixed version to be able to check if incompatibility have been resolved (ex: ffmpeg 3.4, x265 ...)
- [ ] ~~script to test installation~~
- [ ] ~~Add tensorflow from source~~
